/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.*;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.DatosSupLinea;

/**
 *
 * @author gabri
 */
public class VentanaSLinea extends javax.swing.JFrame {

    /**
     * Creates new form VentanaSLinea
     */
    public VentanaSLinea() {
        initComponents();
        this.setLocationRelativeTo(null); // poner la ventana en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jButtonCerrarSesionSL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldHoraInicioSL = new javax.swing.JTextField();
        jTextFieldHoraFinSL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxModelo = new javax.swing.JComboBox<>();
        jComboBoxColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldObjetivoProdSL = new javax.swing.JTextField();
        jButtonIniciarOP = new javax.swing.JButton();
        jButtonReanudarOP = new javax.swing.JButton();
        jButtonFinalizarOP = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonPausarOP = new javax.swing.JButton();
        jEstado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLinea = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxLineaTrabajo = new javax.swing.JComboBox<>();

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ESTADO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 180, 219));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 131, 176));

        jButtonCerrarSesionSL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonCerrarSesionSL.setText("CERRAR SESION");
        jButtonCerrarSesionSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionSLActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORA DE INICIO DEL TURNO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HORA DE FIN DEL TURNO");

        jTextFieldHoraInicioSL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextFieldHoraFinSL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODELO");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("COLOR");

        jComboBoxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "ADIDAS", "NIKE", "PUMA" }));
        jComboBoxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxModeloActionPerformed(evt);
            }
        });

        jComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "BLANCO", "NEGRO", "AZUL" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("OBJETIVO POR HORA DE PRODUCCION");

        jTextFieldObjetivoProdSL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextFieldObjetivoProdSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldObjetivoProdSLActionPerformed(evt);
            }
        });

        jButtonIniciarOP.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciarOP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonIniciarOP.setText("INICIAR OP");
        jButtonIniciarOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarOPActionPerformed(evt);
            }
        });

        jButtonReanudarOP.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReanudarOP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonReanudarOP.setText("REANUDAR OP");
        jButtonReanudarOP.setEnabled(false);
        jButtonReanudarOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReanudarOPActionPerformed(evt);
            }
        });

        jButtonFinalizarOP.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFinalizarOP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonFinalizarOP.setText("FINALIZAR OP");
        jButtonFinalizarOP.setEnabled(false);
        jButtonFinalizarOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFinalizarOPActionPerformed(evt);
            }
        });

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "HORA INICIO", "HORA FIN", "SKU", "OBJETIVO POR HORA", "NRO LINEA DE TRABAJO"
            }
        ));
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonPausarOP.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPausarOP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonPausarOP.setText("PAUSAR OP");
        jButtonPausarOP.setEnabled(false);
        jButtonPausarOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPausarOPActionPerformed(evt);
            }
        });

        jEstado.setEditable(false);
        jEstado.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ESTADO");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nº DE ORDEN DE PRODUCCIÓN");

        jLinea.setEditable(false);
        jLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLineaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NRO DE LINEA DE TRABAJO");

        jComboBoxLineaTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2", "3" }));

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCerrarSesionSL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldHoraInicioSL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonIniciarOP)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxLineaTrabajo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPausarOP)
                                        .addGap(102, 102, 102)
                                        .addComponent(jButtonReanudarOP)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonFinalizarOP))
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldHoraFinSL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldObjetivoProdSL, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHoraInicioSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldHoraFinSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldObjetivoProdSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBoxLineaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciarOP)
                    .addComponent(jButtonReanudarOP)
                    .addComponent(jButtonPausarOP)
                    .addComponent(jButtonFinalizarOP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCerrarSesionSL)
                        .addComponent(jLabel6))
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionSLActionPerformed
        // TODO add your handling code here:
        SupLineaControl.ocultar(); // oculta la ventana principal del sup de linea
        LoginControl.mostrar(); // muestra la ventana para loggearse
    }//GEN-LAST:event_jButtonCerrarSesionSLActionPerformed

    private void jTextFieldObjetivoProdSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldObjetivoProdSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldObjetivoProdSLActionPerformed

    private void jComboBoxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxModeloActionPerformed
    int nro = 0;
    public int nroOP() {
        nro++;
        return nro;         
    }
    private void jButtonIniciarOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarOPActionPerformed
        // TODO add your handling code here:
        eliminar();
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();        
        
        String horaInicio = jTextFieldHoraInicioSL.getText();
        String horaFinal = jTextFieldHoraFinSL.getText();
        String horaProduccion = jTextFieldObjetivoProdSL.getText();
        String modelo = (String)jComboBoxModelo.getSelectedItem();
        String color = (String)jComboBoxColor.getSelectedItem();
        String nroLinea = (String)jComboBoxLineaTrabajo.getSelectedItem();
        jEstado.setText("Iniciado");
        
  
        // class + variable = new class (parametros);
        DatosSupLinea c = new DatosSupLinea(horaInicio,horaFinal,horaProduccion, modelo , color, nroLinea);
        
        calzados.add(c);
        eliminar();
        llenarJTable(); //llama a la funcion "llenar tabla"
        
        jButtonIniciarOP.setEnabled(false); // desabilita el boton iniciarOP cuando damos clic al mismo
        jButtonPausarOP.setEnabled(true); // se habilita el boton pausarOP
        jButtonFinalizarOP.setEnabled(true); // se habilita el boton finalizarOP
        
        //limpia los campos
        
//        jTextFieldHoraInicioSL.setText("");
//        jTextFieldHoraFinSL.setText("");
//        jTextFieldObjetivoProdSL.setText("");
//        jComboBoxModelo.setSelectedIndex(0);
//        jComboBoxColor.setSelectedIndex(0);
        
        // desabilita los campos
        
        jTextFieldHoraInicioSL.setEnabled(false);
        jTextFieldHoraFinSL.setEnabled(false);
        jTextFieldObjetivoProdSL.setEnabled(false);
        jComboBoxModelo.setEnabled(false);
        jComboBoxColor.setEnabled(false);
        jComboBoxLineaTrabajo.setEnabled(false);
        
        
         
    }//GEN-LAST:event_jButtonIniciarOPActionPerformed

    private void jButtonReanudarOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReanudarOPActionPerformed
        // TODO add your handling code here:
        jEstado.setText("Reanudado");
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        

        if(jTable1.getSelectedRowCount()==1){ // controla que la fila selecciona sea solo una
            
            //if(camposHabilitados() == false){
            //toma los valores que hay en los campos
            String horaInicio = jTextFieldHoraInicioSL.getText();
            String horaFinal = jTextFieldHoraFinSL.getText();
            String horaProduccion = jTextFieldObjetivoProdSL.getText();
            String SKU = "DEPOR - "+(String)jComboBoxModelo.getSelectedItem()+" - "+ (String)jComboBoxColor.getSelectedItem();
           // String color = (String)jComboBoxColor.getSelectedItem();
            String nroLinea = (String)jComboBoxLineaTrabajo.getSelectedItem();
            
            
            
            
            // luego actualiza/modifica dichos valores
            datos.setValueAt(horaInicio, jTable1.getSelectedRow(), 0);
            datos.setValueAt(horaFinal, jTable1.getSelectedRow(), 1);
            datos.setValueAt(SKU, jTable1.getSelectedRow(), 2);
           // datos.setValueAt(color, jTable1.getSelectedRow(), 3);
            datos.setValueAt(horaProduccion, jTable1.getSelectedRow(), 3);
            datos.setValueAt(nroLinea, jTable1.getSelectedRow(), 4);
           //datos.setValueAt(estado,jTable1.getSelectedRow(),5);
            }
            //}
            //limpia los campos
        
//            jTextFieldHoraInicioSL.setText("");
//            jTextFieldHoraFinSL.setText("");
//            jTextFieldObjetivoProdSL.setText("");
//            jComboBoxModelo.setSelectedIndex(0);
//            jComboBoxColor.setSelectedIndex(0);
            
            
            jButtonReanudarOP.setEnabled(false); //se desabilita el boton reanudarOP
            jButtonPausarOP.setEnabled(true); // se habilita el boton pausarOP
            jButtonFinalizarOP.setEnabled(true); // se habilita el boton finalizarOP
            
            // desabilitar los campos
        
            jTextFieldHoraInicioSL.setEnabled(false);
            jTextFieldHoraFinSL.setEnabled(false);
            jTextFieldObjetivoProdSL.setEnabled(false);
            jComboBoxModelo.setEnabled(false);
            jComboBoxColor.setEnabled(false);
            jComboBoxLineaTrabajo.setEnabled(false);
        

    }//GEN-LAST:event_jButtonReanudarOPActionPerformed
public void eliminar(){ 
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int a = jTable1.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
    }
    private void jButtonFinalizarOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFinalizarOPActionPerformed
        jEstado.setText("Finalizado");
        jLinea.setText("");
        eliminar();
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        jButtonIniciarOP.setEnabled(true); //se hablita boton iniciar 
        jButtonPausarOP.setEnabled(false); // se desabilita el boton pausarOP
        jButtonFinalizarOP.setEnabled(false); // se desabilita el boton finalizarOP
        jButtonReanudarOP.setEnabled(false); // se desabilita el boton reanudarOP
        
        jTextFieldHoraInicioSL.setText("");
        jTextFieldHoraFinSL.setText("");
        jTextFieldObjetivoProdSL.setText("");
        jComboBoxModelo.setSelectedIndex(0);
        jComboBoxColor.setSelectedIndex(0);
        
        //Se habilitan los campo
        jTextFieldHoraInicioSL.setEnabled(true);
        jTextFieldHoraFinSL.setEnabled(true);
        jTextFieldObjetivoProdSL.setEnabled(true);
        jComboBoxModelo.setEnabled(true);
        jComboBoxColor.setEnabled(true);
        jComboBoxLineaTrabajo.setEnabled(true);
        
    }//GEN-LAST:event_jButtonFinalizarOPActionPerformed
    public boolean camposHabilitados(){
            
        jTextFieldHoraInicioSL.setEnabled(true);
        jTextFieldHoraFinSL.setEnabled(true);
        jTextFieldObjetivoProdSL.setEnabled(true);
        jComboBoxModelo.setEnabled(true);
        jComboBoxColor.setEnabled(true);
        jComboBoxLineaTrabajo.setEnabled(true);
   
        return true;
    }
    private void jButtonPausarOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPausarOPActionPerformed
        // TODO add your handling code here:
        jEstado.setText("Pausado");
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
                
        //limpia los campos
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea modificar algun campo?", "Seleccione una opcion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(respuesta == JOptionPane.YES_OPTION){
            
            // se habilitan los campos
            camposHabilitados();
           
            
        }else if(respuesta == JOptionPane.NO_OPTION){
            
            // desabilita los campos
        
            jTextFieldHoraInicioSL.setEnabled(false);
            jTextFieldHoraFinSL.setEnabled(false);
            jTextFieldObjetivoProdSL.setEnabled(false);
            jComboBoxModelo.setEnabled(false);
            jComboBoxColor.setEnabled(false);
            jComboBoxLineaTrabajo.setEnabled(false);
            
        }           
         
        jButtonPausarOP.setEnabled(false); // se desabilita el boton pausarOP
        jButtonFinalizarOP.setEnabled(false); // se desabilita el boton finalizarOP
        jButtonReanudarOP.setEnabled(true); // se habilita el boton reanudarOP
        
        
    }//GEN-LAST:event_jButtonPausarOPActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        int nfila = jTable1.getSelectedRow();;

        if(nfila>=0){
            //Los numeros son el nro de columna al que pertenece
            
            String horaInicio = datos.getValueAt(nfila, 0).toString();
            String horaFin = datos.getValueAt(nfila, 1).toString();
            String modelo = datos.getValueAt(nfila, 2).toString();
            String color = datos.getValueAt(nfila, 3).toString();
            String objetivoHora = datos.getValueAt(nfila, 4).toString();
        
        
            //Mostramos


            jTextFieldHoraInicioSL.setText(horaInicio);
            jTextFieldHoraFinSL.setText(horaFin);
            jTextFieldObjetivoProdSL.setText(objetivoHora);
            jComboBoxModelo.setSelectedItem(modelo);
            jComboBoxColor.setSelectedItem(color);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLineaActionPerformed
    
    }//GEN-LAST:event_jLineaActionPerformed


    public void llenarJTable(){

        DefaultTableModel datos = (DefaultTableModel) jTable1.getModel();
        // recorrer las filas que tenemos, que vamos cargando y los pasamos al modelo
        
        datos.setNumRows(0); // hace que al cargar una nueva orden, no se dupliquen los datos
        jLinea.setText(""+nroOP());
        for (DatosSupLinea calzado : calzados) {
            eliminar();
            Object[] fila = {calzado.getHoraInicio(), calzado.getHoraFinal(), "DEPOR - " +calzado.getModelo()+" - " +calzado.getColor(),calzado.getHoraProduccion(), calzado.getNroLinea()};
            datos.addRow(fila);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSLinea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSLinea().setVisible(true);
            }
        });
    }

    public JComboBox<String> getjComboBoxColor() {
        return jComboBoxColor;
    }
    
    public JComboBox<String> getjComboBoxLineaTrabajo() {
        return jComboBoxLineaTrabajo;
    }
    

    public JComboBox<String> getjComboBoxModelo() {
        return jComboBoxModelo;
    }

    public JTextField getjTextFieldHoraFinSL() {
        return jTextFieldHoraFinSL;
    }

    public JTextField getjTextFieldHoraInicioSL() {
        return jTextFieldHoraInicioSL;
    }

    public JTextField getjTextFieldObjetivoProdSL() {
        return jTextFieldObjetivoProdSL;
    }
    
    ArrayList<DatosSupLinea> calzados = new ArrayList<DatosSupLinea>();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesionSL;
    private javax.swing.JButton jButtonFinalizarOP;
    private javax.swing.JButton jButtonIniciarOP;
    private javax.swing.JButton jButtonPausarOP;
    private javax.swing.JButton jButtonReanudarOP;
    private javax.swing.JComboBox<String> jComboBoxColor;
    private javax.swing.JComboBox<String> jComboBoxLineaTrabajo;
    private javax.swing.JComboBox<String> jComboBoxModelo;
    private javax.swing.JTextField jEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLinea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldHoraFinSL;
    private javax.swing.JTextField jTextFieldHoraInicioSL;
    private javax.swing.JTextField jTextFieldObjetivoProdSL;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

    
}
